### ISSUE TITLE
Improve argument parsing

### ISSUE THREAD

**Issue by Spindel** [lsrdg/Tatoeba-query#4]
The argparse code is all over the file, and should be brought down to only be used in a single place.

This code should set up the arg parser, and extract the data necessary from it into variables, and then call functions as needed.

The rest of the code should then not need to know anything about the commandline arguments or argparse.

fex:
```python3
def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("-l", help="List languages and their abbreviation", nargs=1)
  args = parser.parse_args()
    
  if args.l:
     searchPattern = args.l[0]
     find_abbrevation(searchPattern)
  else:
       .....
```

**Comment by lsrdg** [comment]
Hey, thanks for passing by/

> The argparse code is all over the file, and should be brought down to only be used in a single place.

That would be amazing, it would help a lot to have a more readable code and only one place to check when there's something wrong with the parser.

> This code should set up the arg parser, and extract the data necessary from it into variables, and then call functions as needed.
The rest of the code should then not need to know anything about the commandline arguments or argparse.

That's a really cleaner way of seeing how things should work. I'll certainly
experiment with that code. However, I would like to change from using optional
arguments (e.g: `-l`) to using a proper positional argument (e.g: `list`), but
I recall that I didn't manage to make the positional arguments play well with 
the `if` block (as you showed), only the optional arguments worked... but I doubt
they are correctly being used... I always need to lookup the code to figure out
which command I need. :P

I was considering using `main()` to call an argparse function which 
would call another function as defined by `parser.set_defaults(func=)`.
Would that be too much for the situation? I was giving it a try [here](https://github.com/lsrdg/cliclock/blob/fd8bc9d04b7ca04dce28dbea51522ff67f427df2/cliclock.py#L97).


Thanks again!

**Comment by Spindel** [comment]
I think that starting simple is better. having all the Argparse code in `main` is a great start.

For developments sake, it's usually better to do one thing at the time, and when you see more improvements to be done, note them down, but don't try to fix everying at once.

Starting simply by moving argument parsing, and keeping the logic as is, helps you in that you'll not be _stuck_ on a problem while you're trying to learn all the other unrelated things.

**Comment by lsrdg** [comment]
Roger.

>For developments sake, it's usually better to do one thing at the time, and when you see more improvements to be done, note them down, but don't try to fix everying at once.
Starting simply by moving argument parsing, and keeping the logic as is, helps you in that you'll not be stuck on a problem while you're trying to learn all the other unrelated things.

Damn, got to remember to come back to read these lines again. 👍

**Comment by lsrdg** [comment]
Just for the sake of "referenceness": it is being implemented on the branch [issue-4-improve-argument-parsing](https://github.com/lsrdg/tatoeba-karini/tree/issue-4-improve-argument-parsing).
