### ISSUE TITLE
More meaninful names to functions

### ISSUE THREAD

**Issue by lsrdg** [lsrdg/Tatoeba-query#5]
As of a feedback from @Spindel:
> Renaming functions based on what they do. `argD` isn't a very good name, since it's unclear what they do. 

Currently the pattern for naming function refers to which optional argument they correspond. Hopefully changing from optional to positonal arguments (#3 ) and improving argument parsing (#4 ) will help on defining better names to functions.

**Comment by Spindel** [comment]
This could also do with the label "Enhancmenet"

**Comment by lsrdg** [comment]
These functions (`argR`, `argS` etc) they were supposed to be a wrapper around
the corresponding functionality.

As I see, the best solution would to change from optional argument (`argF`) to 
a positional argument (`find`). And just then rename the functions accordingly.
If so, this issue would be half handled on issue #4, or at least wait for that.

However, any better idea on how to structure the functions called from `main()`
would be welcomed.

Any thoughts on this?

**Comment by Spindel** [comment]
functions should be named after what they do, and variables / arguments to them based on what they _contain_

**Comment by Spindel** [comment]
Past that, I usually recommend starting with something like this:

```python
def parse_arguments():
  # Set up all arguments here, return "args"

def main():
   args = parse_arguments()
  if args.foobar:
        foobar(args.filename)
```

Not because it's perfect, but because it's rather clear what's going on, and your functions can then be used separately, tested separately, and used in other projects.

**Comment by lsrdg** [comment]
> functions should be named after what they do, and variables / arguments to them based on what they contain

Well explained. 👍
Skipping the thoughts to get here, here is the plan I came to after your last comments:

Considering work on the branch [issue-4-improve-argument-parsing(https://github.com/lsrdg/tatoeba-karini/tree/issue-4-improve-argument-parsing):
- finish the work of gathering the args' variables close to the args
- make use of the positional arguments (`find` and not `argF`) this will improve readability and
make it easier to rename the functions
- open a new branch to rename functions
- merge it
- just then work on `def parse_arguments():...`

Maybe [I wasn't clear at first](https://github.com/lsrdg/tatoeba-karini/issues/4#issuecomment-350589092),
but glad to know that I'm not the only one seeing  that this mess on the functions names affects the whole, specially the argparser...

**Comment by Spindel** [comment]
That's a good and solid plan, go at it.

If you want me to look at it, tag me in the Pull Request, and I'll get a notification.

( I'm going to be away from keyboard for a few days, so don't fret if I'm slow )

**Comment by lsrdg** [comment]
Thanks, @Spindel .
I'll be working on it.

>  I'm going to be away from keyboard

Enjoy ;)

**Comment by lsrdg** [comment]
The solid plan didn't work, ehe.
I couldn't get a way to make the `main()` function work with something like `if args.find...`. The only way I know of doing that involves *first* creating the `parse_arguments()` function and then making it return the value of `func=` or returning the value of the argument passed, as in: https://github.com/lsrdg/cliclock/blob/fd8bc9d04b7ca04dce28dbea51522ff67f427df2/cliclock.py#L74

So, I'll give it a try to rename the functions now, and then adding docstrings to them. Since there's already some progress being done on #14 , #6 will be the only issue missing to achieve the [v0.0.5](https://github.com/lsrdg/tatoeba-karini/milestone/1) milestone.

Changing from flags to commands is an issue by itself and should be treated as well. Maybe set the to the next milestone (v0.0.6)?

**Comment by lsrdg** [comment]
Since #22 those `arg*` functions follow the patter `[COMMAND]Wrapper` as in `downloadWrapper()` in instead of `argD()`.

I guess that a new issue must be created to update any legacy code that still exists (variables, I'm looking at you).

Am I wrong about this? Please, let me know and share it here how could these functions be better named. (:
