### ISSUE TITLE
Reformat code style

### ISSUE THREAD

**Issue by lsrdg** [lsrdg/Tatoeba-query#7]
The code should follow a style guide, at least concerning indentation and blank lines.

**Comment by Spindel** [comment]
When you reformat code according to a style guide, make sure that you _do not_ change other things in the same commit, even if it looks tempting.

It's a _ton_ harder to find a bug when you modify all lines of code _and_ change them, vs. just reformat it.

**Comment by lsrdg** [comment]
Hey @Spindel the code was reformated in #16 .
However, there are 4 errors that were not only typos, under/overindented lines, trailing space etc.
Two of them were actually a bug introduced in #12 and will be fixed in #17 . The other two will have their own issue>branch>pull-request as well.
From now on, I'll keep up with flake8 conventions locally and any other errors will be hopefully spitted out by travis-ci.
