### ISSUE TITLE
CI: run flake8 on all code, automatically

### ISSUE THREAD

**Issue by Spindel** [lsrdg/Tatoeba-query#9]
Travis CI is the default GitHub CI system, so let's use it!

Below is a very simple `.travis-ci.yml` to run flake8 on the code.

Flake8 is an automated python tool that checks if code follows pyflakes and pep8 standards.

https://docs.travis-ci.com/user/getting-started/

```
language: python
python:
  - 3.6
install:
  - pip install flake8
script:
  - flake8 .
```

**Comment by Spindel** [comment]
related to #7

**Comment by lsrdg** [comment]
That's a really good idea. However, the project was originally created on [gitlab](https://gitlab.com/lsrdg/tatoeba-karini), and every time I push to gitlab, it pushes to github. Gitlab has its own `gitlab-ci.yml`.
Need to find out if is it possible to have both (my guess is that they can be both configured to be mutually ignored > one ignoring the other). 

Any thoughts (pros/cons) on keeping the project on both or only in one of them?

**Comment by Spindel** [comment]
GitLab is, imo, a better platform, though it's sometimes a bit slow (boo)

No matter what you chose, you should be clear in the documentation where development happens, and why it does.

You should also close the issue tracker on the one you don't use, and direct people to the one you use.

Pick one, and stick to it, You can always migrate later.

**Comment by lsrdg** [comment]
Thanks for sharing. I'm not ready to take a decison right now, would like to explore a bit more about the topic.

By now, I guess I'll branch out and experiment with both travis and gitlab-ci.

Any input, as always, is welcome. (:

**Comment by lsrdg** [comment]
The development will happen on Github: #18 .

Closing this issue since #15 was already equivocally merged.
Now, gotta make those tests pass. (=
